name: Build and Push to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21  # Adjust this if needed
          distribution: adopt  # Or other options like 'zulu'

      - name: Write environment variables to file

        run: |
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
            echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
            echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env

      
      # - name: Load environment variables
      #   run: |
      #         echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV
      #         echo "DATABASE_USERNAME=$DATABASE_USERNAME" >> $GITHUB_ENV
      #         echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> $GITHUB_ENV
            
      #   env:
      #         DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #         DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      #         DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

      - name: Build with Maven
        run: mvn clean package


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/gym:v1 .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/gym:v1
